### ISSUE TITLE
Modernize dependencies, squash warnings?

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/pytest-check-links#13]
While working on #11, #12, I've found some things annoying.

The following warnings end up in end users test logs:

`plugin.py:168: DeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.`

- just what it says?

`PytestDeprecationWarning: direct construction of CheckLinks has been deprecated, please use CheckLinks.from_parent`

  - require whatever version introduces `from_parent`

Less pressing, but still annoying are our test cases:

`PytestExperimentalApiWarning: testdir.copy_example is an experimental api that may change over time`
  - don't use `copy_example`... just `shutil.copy` into testdir?

Finally, keeping 3.5 and 2.7 happy is annoying
  - perhaps drop them?
  - ...and start testing on `3.9-nightly`?
     - the `MutableMapping`pocalypse hits `html5lib`, `requests-cache`, etc. however
  - probably can't do both at once

**Comment by blink1073** [comment]
Given that 2.7 is past EOL, I say we drop it.  Python 3.5 is still supported in JupyterLab, so I say we keep it for now.  The others I don't see as blockers for release.

**Comment by bollwyvl** [comment]
I don't think any of them are release blockers... Just stuff that bothered
me while down in the guts of the thing, and to create a little SEO juice
for the actual error message texts.

One thing I forgot to mention would be the ability to use lxml if
available, since html5lib can use it transparently... Though the parsing is
rather naive at present, and should probably be lru cached, at least,
before doing _yet more_ dependency stuff.

**Comment by AnnaDinaburgVulikh** [comment]
Hello, this project looks really useful, should I try to fix the deprication errors?

**Comment by bollwyvl** [comment]
@AnnaDinaburgVulikh That would be marvelous!

I think folk have thus far been kinda willing to deal with it, since it's "just" docs, but clean runs benefit everyone!

**Comment by AnnaDinaburgVulikh** [comment]
Hi @bollwyvl , made the fix.

**Comment by bollwyvl** [comment]
Ah, is that the only thing outstanding? Super! PR away, though CI might well not run due to an change on Travis-CI... but good to let folk know/discuss.

**Comment by AnnaDinaburgVulikh** [comment]
Hi @blink1073 , would you like to merge the fix for the deprecation warning? 
Are any adjustments needed due to the change on Travis-CI?

**Comment by blink1073** [comment]
We set up Github Actions in #24, can you please open a pull request with you change @AnnaDinaburgVulikh?
