### ISSUE TITLE
Move to jupyterlab org?

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/pytest-check-links#8]
Hi @minrk, are you opposed to moving this repo to the jupyterlab org?

Short of that, do you mind and adding @vidartf and myself (vidartf and blink1073) as maintainers on PyPI and on the repo?

**Comment by minrk** [comment]
Please feel free! I added you both as owners here and on PyPI. I definitely don't want things living on my own profile that folks really need to use and maintain.

**Comment by blink1073** [comment]
Hi @minrk, we have agreement in https://github.com/jupyterlab/team-compass/issues/46.  I think the best course of action is for you to directly transfer the repo so it there is a clearly defined source.  Then I'll add the Jupyter license on top of yours and cut a patch release.

**Comment by minrk** [comment]
Moved

**Comment by blink1073** [comment]
Thanks, @minrk!  :heart:
